### ISSUE TITLE
SPREAD version 1.0.6 Linux and Windows; hangs/never loads files (example and real .tre files).

### ISSUE THREAD

**Issue by mmelendrez** [phylogeography/SPREAD#7]
Apologies if this is the wrong forum to post this issue in, but there are no man, help or FAQs for this program so I had no idea how to troubleshoot this and could not find the answer in the beast-users googlegroup.

1. I downloaded and extract the .tgz Linux version of SPREAD
2. I am running RedHat OS 6.5
3. It appeared to extract just fine and I had spread in the /bin and spread.jar in the /lib along with all other files.
4. I had to make the files executable ```chmod 777 ~/bin/SPREAD_v1.0.6/bin/spread``` and ```chmod 777 ~/bin/SPREAD_v1.0.6/lib/spread.jar```
5. I then tried ``` ~/bin/SPREAD_v1.0.6/bin/spread``` and the program opened just fine.
6. I went to load a tree file (the example H5N1 provided at http://www.kuleuven.be/aidslab/phylogeography/SPREAD.html)
7. I waited 20 min the file would not load. There is no error output, no output in the terminal tab, no output in the terminal where I activate the program with ```~/bin/SPREAD_v1.0.6/bin/spread```

I then tried this same process giving the program more memory:
```
java -jar -Xms1024m -Xmx12288m ~/bin/SPREAD_v1.0.6/lib/spread.jar
```
Program opened but I could not load any file - it hung same as before.

As you can see by the figures, the bottom status bar says the file was loaded, but the terminal tab shows no output verifying the file was loaded.
![spread1](https://cloud.githubusercontent.com/assets/2855130/6397668/5213cfae-bdb4-11e4-85c5-4a9ada1b09d3.jpg)
![spread2](https://cloud.githubusercontent.com/assets/2855130/6397667/5213ca2c-bdb4-11e4-9334-76133f73670a.jpg)

I am unable to click on anything else in the program. If I were to assume the file was loaded and click on "Setup location coordinates:" I get the following popup error and terminal output:
popup box error:
![spread3](https://cloud.githubusercontent.com/assets/2855130/6397709/ab456fe2-bdb4-11e4-8f12-17383a4f0412.jpg)

and terminal output:
```
java.lang.ClassCastException: [Ljava.lang.Object; incompatible with java.lang.String
	at utils.Utils.getStringNodeAttribute(Unknown Source)
	at gui.LocationCoordinatesEditor.getUniqueTreeStates(Unknown Source)
	at gui.LocationCoordinatesEditor.launch(Unknown Source)
	at gui.DiscreteModelTab$ListenOpenLocationCoordinatesEditor.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2029)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2352)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:413)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:270)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:263)
	at java.awt.Component.processMouseEvent(Component.java:6520)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3331)
	at java.awt.Component.processEvent(Component.java:6285)
	at java.awt.Container.processEvent(Container.java:2240)
	at java.awt.Component.dispatchEventImpl(Component.java:4876)
	at java.awt.Container.dispatchEventImpl(Container.java:2298)
	at java.awt.Component.dispatchEvent(Component.java:4702)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4843)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4503)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4433)
	at java.awt.Container.dispatchEventImpl(Container.java:2284)
	at java.awt.Window.dispatchEventImpl(Window.java:2730)
	at java.awt.Component.dispatchEvent(Component.java:4702)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$200(EventQueue.java:114)
	at java.awt.EventQueue$3.run(EventQueue.java:705)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(AccessController.java:300)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(AccessController.java:300)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:253)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:172)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:157)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:149)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:102)
```
I tried this entire process again by downloading to my Windows 7 the SPREAD zip for Windows. In this download/extraction there was SPREAD.exe and /lib/spread.jar. I tried both - same problem and outputs as above both times.

Are there dependencies I potentially lacking? The example .tre file looks correct and does not load. I've attached both .tre files (I just appended w/ .png to get them to load on github).
![den1_ro1_genomes_03feb15_discrete500_bssvs_mcc tre](https://cloud.githubusercontent.com/assets/2855130/6397844/a6fb761a-bdb5-11e4-8a8a-31c1296d774a.png)
![h5n1_ha_discrete_mcc tre](https://cloud.githubusercontent.com/assets/2855130/6397843/a6faab9a-bdb5-11e4-832a-4cc82f485059.png)

Please advise.

Thanks.

**Comment by fbielejec** [comment]
I cannot reproduce the behavior you are describing. I can load both files you have included and open the coordinates editor without the program freezing. Perhaps you're not choosing the right states attribute name? I believe it's called "location" in one of your tree files and "states" in the other.

**Comment by mmelendrez** [comment]
I am wondering then if I am missing something in the download then. Because I cannot even load the files. Did they take a long time to load? I waited about 20 min per file and got nothing to load. Perhaps it's my system set ups...Windows 7 and RedHat 6.5? A friend tested the Mac version and also got everything to load, but another friend loaded on his Linux and got the same issues - so I guess it must be something with our system set ups. I knew about the 'location' issue but I can't even get that far because the files won't load. Odd.

**Comment by mmelendrez** [comment]
Ok I went back to the .zip file for Windows and re-extracted using a different command - this time it gave me a folder called SPREAD v1.0.6 and inside that folder was SPREAD v1.0.6 and META-INF. I double clicked the .exe for SPREAD and was able to get my file to load - not the prettiest (it cuts off my attribute states dropdown) but I did get it to load. Will double check the Linux version...
![capture](https://cloud.githubusercontent.com/assets/2855130/6414144/5031b836-be63-11e4-9f3f-6616687cdcc3.JPG)

**Comment by mmelendrez** [comment]
Great - so I got it working on my Linux with the same issue above the dropdown menu was cutoff, so when I'd tried it the first few times yesterday the state attibute menu was cut off so I didn't click into it. Today I clicked into it and it doesn't stay open long enough for me to scroll to location, but I was able to reach location by using arrows on my keyboard.

Thanks for your responses.

**Comment by ahwll** [comment]
I can not open the setup button to import the location coordinates. How to solve this problem?

**Comment by fbielejec** [comment]
Hi, SPREAD is no longer actively maintained - you might want to consider using [SpreaD3](https://github.com/phylogeography/SpreaD3)

**Comment by AgustinPardo** [comment]
Same problem!
![Screenshot from 2020-07-27 12-39-59](https://user-images.githubusercontent.com/14830537/88561931-6de00300-d006-11ea-8f6c-c88912ea6a66.png)
